Repository deshima-dev/deshima-sensitivity, pull requests merged in 2020-09, with the labels that each got.

#41 Add documentation
  .github/workflows/gh-pages.yml
  .gitignore
  README.md
  deshima_sensitivity/__init__.py
  deshima_sensitivity/atmosphere.py
  deshima_sensitivity/galaxy.py
  docs/_static/logo.png
  docs/conf.py
  docs/index.rst
  etc/builddoc
  poetry.lock
  pyproject.toml
Labels: docs

#43 Release v0.2.4
  README.md
  deshima_sensitivity/__init__.py
  docs/conf.py
  docs/index.rst
  pyproject.toml
  sensitivity.ipynb
  tests/test_package.py
Labels: release

#45 Rename script for building docs
  etc/builddocs
Labels: bug

#47 Use README.md as a top page of the docs
  .github/workflows/gh-pages.yml
  README.md
  docs/index.rst
  etc/builddocs
Labels: docs, feature

#49 Release v0.2.5
  README.md
  deshima_sensitivity/__init__.py
  docs/conf.py
  pyproject.toml
  sensitivity.ipynb
  tests/test_package.py
Labels: release
